---
# Traefik L2 LoadBalancer Service for IPv4
apiVersion: v1
kind: Service
metadata:
  name: traefik-l2-lb-v4
  namespace: traefik  # same namespace as your Traefik example
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.240  # first IP from your IPAddressPool
  externalTrafficPolicy: Local  # Required to set the IP Address correctly
  selector:
    app.kubernetes.io/instance: traefik-traefik
    app.kubernetes.io/name: traefik
  ports:
    - port: 80
      targetPort: 80
      name: web
    - port: 443
      targetPort: 443
      name: websecure
