apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: traefik-forward-auth
  namespace: traefik
spec:
  organizationId: f099b749-dbb1-4b0a-92d2-ada2016aae47
  secretName: traefik-forward-auth-secrets
  authToken:
    secretName: bw-auth-token
    secretKey: token
  map:
    - bwSecretId: 4970b8b3-d677-4ccb-be4d-b3d501608a44
      secretKeyName: google_client_id

    - bwSecretId: a94c9b6c-f001-40c5-aa86-b3d50160ebe1
      secretKeyName: google_client_secret

    - bwSecretId: 42047469-dcdf-45ce-9932-b3d501614d78
      secretKeyName: oauth_secret
